services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: Mitya
      POSTGRES_PASSWORD: Baburin17! 
      POSTGRES_DB: dataproject
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 dating_platform.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: